apiVersion: v1
kind: Pod
metadata: 
  name: kubia-liveness
spec:
  containers:
  - image: luksa/kubia-unhealthy
    name: kubia
    resources:
      requests:
        memory: "50Mi"
        cpu: 50m
      limits:
        memory: "80Mi"
        cpu: 80m
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10