apiVersion: v1
kind: Pod
metadata:
  name: curl-custom-sa
spec:
  serviceAccount: foo
  containers:
  - name: main
    image: curlimages/curl
    command: ["sleep","99999"]
  - name: ambassador
    image: luksa/kubectl-proxy:1.6.2