apiVersion: v1
kind: Pod
metadata: 
  name: fortune-pod-configmap-part-volume
spec:
  containers: 
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: config
      mountPath: /etc/nginx/conf.d/gzip.conf # whole path
      subPath: gzip.conf
      readOnly: true
  volumes:
  - name: config
    configMap:
      name: fortune-config-multiple
      items:
      - key: my-nginx-config.conf
        path: gzip.conf