apiVersion: v1
kind: Pod
metadata: 
  name: fortune-env-from-configmap
spec:
  containers: 
  - image: luksa/fortune:env
    name: html-generator
    envFrom:
    - prefix: CONFIG_
      configMapRef:
        name: fortune-config
    env:
    - name: INTERVAL
      valueFrom:
        configMapKeyRef:
          name: fortune-config
          key: sleep-interval