apiVersion: v1
kind: Pod
metadata:
  name: curl-with-ambassador
spec:
  containers:
  - name: main
    image: curlimages/curl
    command: ["sleep", "999999"]
    resources:
        requests:
          cpu: 250m
          memory: 0.5Gi
        limits:
          cpu: 250m
          memory: 0.5Gi
  - name: ambassador
    image: luksa/kubectl-proxy
    resources:
        requests:
          cpu: 250m
          memory: 0.5Gi
        limits:
          cpu: 250m
          memory: 0.5Gi