apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubia-frontend
  template:
    metadata:
      name: kubia-frontend
      labels:
        app: kubia-frontend
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: kubia
      containers:
      - image: luksa/kubia:v1
        name: nodejs