apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      nodeSelector:
       bpu: "true"
      containers:
      - image: luksa/kubia:v1
        name: nodejs