apiVersion: v1
kind: ResourceQuota
metadata:
  name: objects
spec:
  hard:
    pods: 2
    replicationcontrollers: 5 
    secrets: 10 
    configmaps: 10 
    persistentvolumeclaims: 4 
    services: 5 
    services.loadbalancers: 1 
    services.nodeports: 2 
    ssd.storageclass.storage.k8s.io/persistentvolumeclaims: 2