apiVersion: v1
kind: Pod
metadata: 
  name: requests-pod-too-big
spec:
  containers:
  - image: busybox
    command: ["dd", "if=/dev/zero","of=/dev/null"]
    name: main
    resources:
      requests:
        cpu: 2
        memory: 10Gi