apiVersion: v1
kind: Pod
metadata: 
  name: requests-3-pod
spec:
  containers:
  - image: busybox
    command: ["dd", "if=/dev/zero","of=/dev/null"]
    name: main
    resources:
      requests:
        cpu: 20
        memory: 10Gi